routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/order', function () {
    return view('pembeli.order');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// GET EACH PAGE WITH RESOURCES
Route::resource('/adminUtama', 'AdminController');
Route::resource('/kandang', 'KandangController')->middleware('peternak');
Route::resource('/pembeli', 'PembeliController')->middleware('penjual');
Route::resource('/transaksi', 'TransaksiController');
Route::get('/tableTransaksi', 'TransaksiController@tampilTransaksiTabel');

resources/views/admin/create.blade.php
@extends('master._layout')

@section('title', 'Buat User')

@section('content')
<div class="container p-5">
    <div class="card-box">
        <h5>Buat User Baru</h5>

        <form method="POST" action="/adminUtama">
            @csrf

            <div class="form-group row">
                <label for="username" class="col-md-4 col-form-label text-md-left">{{ __('Username') }}</label>

                <div class="col-md-6">
                    <input id="username" type="text"
                        class="form-control{{ $errors->has('username') ? ' is-invalid' : '' }}" name="username"
                        value="{{ old('username') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-left">{{ __('Name') }}</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                        name="name" value="{{ old('name') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-left">{{ __('E-Mail Address') }}</label>

                <div class="col-md-6">
                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                        name="email" value="{{ old('email') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="password" class="col-md-4 col-form-label text-md-left">{{ __('Password') }}</label>

                <div class="col-md-6">
                    <input id="password" type="password"
                        class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password"
                        required>
                </div>
            </div>

            <div class="form-group row">
                <label for="password-confirm"
                    class="col-md-4 col-form-label text-md-left">{{ __('Confirm Password') }}</label>

                <div class="col-md-6">
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation"
                        required>
                </div>
            </div>

            <div class="form-group row">
                <label for="group" class="col-md-4 col-form-label text-md-left">{{ __('ID Group') }}</label>

                <div class="col-md-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="inputGroupSelect01">Group</label>
                        </div>
                        <select class="custom-select" id="inputGroupSelect01" name="group">
                            <option>Pilih...</option>
                            <option value="2" @if(old('group')=='2' )selected @endif>Pembeli</option>
                            <option value="3" @if(old('group')=='3' )selected @endif>Peternak</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label for="alamat" class="col-md-4 col-form-label text-md-left">{{ __('Alamat') }}</label>

                <div class="col-md-6">
                    <input id="alamat" type="text" class="form-control{{ $errors->has('alamat') ? ' is-invalid' : '' }}"
                        name="alamat" value="{{ old('alamat') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="kota" class="col-md-4 col-form-label text-md-left">{{ __('Kota') }}</label>

                <div class="col-md-6">
                    <input id="kota" type="text" class="form-control{{ $errors->has('kota') ? ' is-invalid' : '' }}"
                        name="kota" value="{{ old('kota') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="telepon" class="col-md-4 col-form-label text-md-left">{{ __('Telepon') }}</label>

                <div class="col-md-6">
                    <input id="telepon" type="text"
                        class="form-control{{ $errors->has('telepon') ? ' is-invalid' : '' }}" name="telepon"
                        value="{{ old('telepon') }}" required>
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Register') }}
                    </button>
                </div>
            </div>

            @include('error')
        </form>
    </div>
</div>
@endsection

resources/views/admin/edit.blade.php
@extends('master._layout')

@section('title', 'Edit User')

@section('content')
<div class="container p-5">
    <div class="card-box">
        <h5>Edit User</h5>

        <form method="POST" action="{{ route('adminUtama.update', $user->id) }}">
            @method('PATCH')
            @csrf

            <div class="form-group row">
                <label for="username" class="col-md-4 col-form-label text-md-left">{{ __('Username') }}</label>

                <div class="col-md-6">
                    <input id="username" type="text"
                        class="form-control" name="username"
                        value="{{ $user->username }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="name" class="col-md-4 col-form-label text-md-left">{{ __('Name') }}</label>

                <div class="col-md-6">
                    <input id="name" type="text" class="form-control"
                        name="name" value="{{ $user->name }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="email" class="col-md-4 col-form-label text-md-left">{{ __('E-Mail Address') }}</label>

                <div class="col-md-6">
                    <input id="email" type="email" class="form-control"
                        name="email" value="{{ $user->email }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="password" class="col-md-4 col-form-label text-md-left">{{ __('Password') }}</label>

                <div class="col-md-6">
                    <input id="password" type="password" class="form-control" name="password">
                </div>
            </div>

            <div class="form-group row">
                <label for="password-confirm"
                    class="col-md-4 col-form-label text-md-left">{{ __('Confirm Password') }}</label>

                <div class="col-md-6">
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" >
                </div>
            </div>

            <div class="form-group row">
                <label for="group" class="col-md-4 col-form-label text-md-left">{{ __('ID Group') }}</label>

                <div class="col-md-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="inputGroupSelect01">Group</label>
                        </div>
                        <select class="custom-select" id="inputGroupSelect01" name="group">
                            <option value="{{ $user->group }}">{{ $user->group }}</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label for="alamat" class="col-md-4 col-form-label text-md-left">{{ __('Alamat') }}</label>

                <div class="col-md-6">
                    <input id="alamat" type="text" class="form-control"
                        name="alamat" value="{{ $user->alamat }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="kota" class="col-md-4 col-form-label text-md-left">{{ __('Kota') }}</label>

                <div class="col-md-6">
                    <input id="kota" type="text" class="form-control"
                        name="kota" value="{{ $user->kota }}">
                </div>
            </div>

            <div class="form-group row">
                <label for="telepon" class="col-md-4 col-form-label text-md-left">{{ __('Telepon') }}</label>

                <div class="col-md-6">
                    <input id="telepon" type="text"
                        class="form-control" name="telepon"
                        value="{{ $user->telepon }}">
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-info">
                        {{ __('Edit') }}
                    </button>
                </div>
            </div>

            @include('error')
        </form>
    </div>
</div>
@endsection

resources/views/admin/index.blade.php
@extends('master._layout')

@section('title', 'Super Admin')

@section('content')

<div class="container mt-2">
    <div class="card-box">
        <ul class="ul-nav">
            <li><a href="/adminUtama" class="btn btn-info">Home</a></li>
            <li>
                <a class="btn btn-dark" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();"> {{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
        </ul>
    </div>
</div>

<div class="container pt-2">
    <div class="card-box">
        <h3>Selamat datang di Halaman Super Admin..</h3>
    </div>
</div>

<div class="container pt-4">
    <div class="m-2 p-2">
        <a href="/adminUtama/create" class="btn btn-success"> <i class="fa fa-plus"></i> Tambah User</a>

    </div>
    
    <div class="card-box">
        <table class="table table-hover table-bordered table-responsive-lg">
             <?php $i=1; ?>
            <thead class="thead-dark">
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Username</th>
                    <th scope="col">Name</th>
                    <th scope="col">Group</th>
                    <th scope="col">Alamat</th>
                    <th scope="col">Kota</th>
                    <th scope="col">Telepon</th>
                    <th scope="col">Email</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($users as $user)
                <tr>
                    <td> {{ $i++ }} </td>
                    <td> {{ $user->username }} </td>
                    <td> {{ $user->name }} </td>
                    <td> {{ $user->group }} </td>
                    <td> {{ $user->alamat }} </td>
                    <td> {{ $user->kota }} </td>
                    <td> {{ $user->telepon }} </td>
                    <td> {{ $user->email }} </td>
                    <td>
                        <a class="btn btn-warning" href="{{ route('adminUtama.edit',$user->id)}}"><i class="fa fa-cog"></i> Edit</a> <br>
                        <div class="mt-2"></div>
                        {{-- <a class="btn btn-danger"><i class="fa fa-trash"></i> Delete</a> --}}
                        <form action="{{ route('adminUtama.destroy', $user->id)}}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i> Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/admin/show.blade.php
@extends('master._layout')

@section('title', 'Lihat User')

@section('content')

@endsection