routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/order', function () {
    return view('pembeli.order');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// GET EACH PAGE WITH RESOURCES
Route::resource('/adminUtama', 'AdminController');
Route::resource('/kandang', 'KandangController')->middleware('peternak');
Route::resource('/pembeli', 'PembeliController')->middleware('penjual');
Route::resource('/transaksi', 'TransaksiController');
Route::get('/tableTransaksi', 'TransaksiController@tampilTransaksiTabel');

app/Transaksi.php
<?php

namespace Peternakan;

use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    protected $fillable = [
        'peternak_id', 'pembeli_id', 'nama', 'alamat', 'jumlah'
    ];

    public function kandangs()
    {
        return $this->belongsTo('Peternakan\Kandang', 'peternak_id');
    }

    public function pembelis()
    {
        return $this->belongsTo('Peternakan\Pembeli', 'pembeli_id');
    }
}

app/Http/Controllers/TransaksiController.php
<?php

namespace Peternakan\Http\Controllers;

use Peternakan\Transaksi;
use Illuminate\Http\Request;
use Peternakan\User;
use Peternakan\Kandang;
use Peternakan\Pembeli;
use Auth;
use Illuminate\Support\Facades\DB;

class TransaksiController extends Controller
{
    public function index()
    {
        return view('transaksi.index');
    }

    public function create()
    {
        $user = Auth::user();
        $pembelis = $user->pembeli;
        return view('transaksi.create', compact('pembelis', 'kandangs'));
    }

    public function store(Request $request)
    {               
        $this->validate($request, [
            'peternak_id' => 'required',
            'pembeli_id' => 'required',
            'nama' => 'required|min:3',
            'alamat' => 'required|min:5',
            'jumlah' => 'required',
        ]);

        $transaksi = New Transaksi();
        $transaksi->peternak_id     = $request->peternak_id;
        $transaksi->pembeli_id      = $request->pembeli_id;
        $transaksi->nama            = $request->nama;
        $transaksi->alamat          = $request->alamat;
        $transaksi->jumlah          = $request->jumlah;
        $transaksi->save();

        $kandang = Kandang::where('id', '=', $request->peternak_id)->first();
        $stok = $kandang->stok;
        $hasil = $stok - $request->jumlah;
        $kandang = $kandang::find($request->peternak_id);
        $kandang->stok = $hasil;
        if ($stok == 0 || $hasil > $stok) {
            return redirect('pembeli')->with('error','Tidak Dapat Melakukan Order');
        }
        $kandang->update();

        return redirect('pembeli')->with('success','Berhasil Order');


    }


    public function show($id)
    {
        $user = Auth::user();
        $pembeli = $user->pembeli->first();
        $peternak = Kandang::find($id);
        return view('transaksi.show', compact('pembeli', 'peternak'));
    }

    public function edit(Transaksi $transaksi)
    {
        
    }

    public function update(Request $request, Transaksi $transaksi)
    {
        
    }

    public function destroy(Transaksi $transaksi)
    {
        
    }

    public function tampilTransaksiTabel()
    {
        $user = Auth::user();
        $pembeli = $user->pembeli;
        $transaksis = Transaksi::all();
        return view('transaksi.tampil-table', compact('pembeli', 'transaksis'));
    }
}

resources/views/transaksi/create.blade.php
@extends('master._layout')

@section('title', 'Buat Order')

<div class="container">
    <div class="card-box">
        <div class="d-flex justify-content-between align-items-center">
            <div class="box">
                <a href="/pembeli" class="btn btn-info">Home</a>
            </div>
            <div class="sidebar__logout">
                <a class="btn btn-dark" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();"> {{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>
    </div>
</div>

@section('content')
<div class="container p-5">
    <div class="card-box">
        <h5>Buat Order Baru</h5>

        <form method="POST" action="{{ route('transaksi.store') }}">
            @csrf

            <div class="form-group row">
                <label for="peternak"
                    class="col-md-4 col-form-label text-md-left">{{ __('Nama Peternak') }}</label>

                <div class="col-md-6">
                    <div class="input-group mb-3">
                        <p>: {{ $kandangs->username }}</p>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label for="group"
                    class="col-md-4 col-form-label text-md-left">{{ __('Nama Pembeli') }}</label>

                <div class="col-md-6">
                    <div class="input-group mb-3">
                        @foreach ($pembelis as $pembeli)
                            <p>: {{ $pembeli->username }}</p>
                        @endforeach
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label for="nama" class="col-md-4 col-form-label text-md-left">{{ __('Nama') }}</label>

                <div class="col-md-6">
                    <input id="nama" type="text" class="form-control"
                        name="nama" value="{{ old('nama') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="alamat" class="col-md-4 col-form-label text-md-left">{{ __('Alamat Penerima') }}</label>

                <div class="col-md-6">
                    <input id="alamat" type="text" class="form-control"
                        name="alamat" value="{{ old('alamat') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="jumlah" class="col-md-4 col-form-label text-md-left">{{ __('Jumlah') }}</label>

                <div class="col-md-6">
                    <input id="jumlah" type="text" class="form-control"
                        name="jumlah" value="{{ old('stok') }}" required>
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Order') }}
                    </button>
                </div>
            </div>

            @include('error')
        </form>
    </div>
</div>
@endsection

resources/views/transaksi/show.blade.php
@extends('master._layout')

@section('title', 'Buat Order')


@section('content')
<div class="container">
    <div class="card-box">
        <div class="d-flex justify-content-between align-items-center">
            <div class="box">
                <a href="/pembeli" class="btn btn-info">Home</a>
            </div>
            <div class="sidebar__logout">
                <a class="btn btn-dark" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();"> {{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>
    </div>
</div>

<div class="container p-5">
    <div class="card-box">
        <h5>Buat Order Baru</h5>

        <form method="POST" action="{{ route('transaksi.store') }}">
            @csrf

            <div class="form-group row">
                <label for="peternak_id" class="col-md-4 col-form-label text-md-left">{{ __('Nama Peternak') }}</label>

                <div class="col-md-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="peternak_1">{{ $peternak->user->username }} ~ (Stok :
                                {{$peternak->stok}})</label>
                        </div>
                        <select class="custom-select" id="peternak_1" name="peternak_id">
                            <option {{ old('peternak_id') == $peternak->id ? "selected" : "" }}
                                value="{{ $peternak->id }}">Peternak ID : {{$peternak->id}}</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label for="pembeli_id" class="col-md-4 col-form-label text-md-left">{{ __('Nama Pembeli') }}</label>

                <div class="col-md-6">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="pembeli_id">{{ $pembeli->user->username }}</label>
                        </div>
                        <select class="custom-select" id="pembeli_id" name="pembeli_id">
                            <option {{ old('pembeli_id') == $pembeli->id ? "selected" : "" }}
                                value="{{ $pembeli->id }}">Pembeli ID :
                                {{$pembeli->id}}</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label for="nama" class="col-md-4 col-form-label text-md-left">{{ __('Nama') }}</label>

                <div class="col-md-6">
                    <input id="nama" type="text" class="form-control" name="nama" value="{{ old('nama') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="alamat" class="col-md-4 col-form-label text-md-left">{{ __('Alamat Penerima') }}</label>

                <div class="col-md-6">
                    <input id="alamat" type="text" class="form-control" name="alamat" value="{{ old('alamat') }}"
                        required>
                </div>
            </div>

            <div class="form-group row">
                <label for="jumlah" class="col-md-4 col-form-label text-md-left">{{ __('Jumlah') }}</label>

                <div class="col-md-6">
                    <input id="jumlah" type="text" class="form-control" name="jumlah" value="{{ old('jumlah') }}"
                        required>
                </div>
            </div>

            {{-- <div class="mb-2">
                <input class="form-control" id="totalBayar" type="text"
                    placeholder="Anda Akan Dikenakan Biaya Sebesar {{ number_format($peternak->stok * $peternak->harga, 2, ',', '.') }}"
                    readonly>
            </div> --}}

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Order') }}
                    </button>
                </div>
            </div>

            @include('error')
        </form>
    </div>
</div>
@endsection

@push('scripts')
<script type="text/javascript">

</script>
@endpush

resources/views/transaksi/tampil-table.blade.php
@extends('master._layout') @section('title', 'Transaksi Penjual dan Peternak')

<div class="container">
    <div class="card-box">
        <div class="d-flex justify-content-between align-items-center">
            <div class="box">
                <a href="/pembeli" class="btn btn-info">Home</a>
            </div>
            <div class="sidebar__logout">
                <a class="btn btn-dark" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();"> {{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </div>
    </div>
</div>

@section('content')
<div class="container pt-4">
    @foreach ($pembeli as $pembeli)
        <div class="card-box">
            <h3>Selamat datang, <span class="badge badge-dark">{{ $pembeli->user->username }}</span></h3>
            <p>Berikut adalah History Transaksi anda</p>
        </div>
    @endforeach
</div>

<div class="container">
    <div class="card-box">
        <table class="table table-hover table-bordered table-responsive-lg">
             <?php $i=1; ?>
            <thead class="thead-dark">
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">Peternak</th>
                    <th scope="col">Pembeli</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Alamat</th>
                    <th scope="col">Jumlah</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($transaksis as $transaksi)
                <tr>
                    <td> {{ $i++ }} </td>
                    <td> {{ $transaksi->peternak_id }} </td>
                    <td> {{ $transaksi->pembeli_id }} </td>
                    <td> {{ $transaksi->nama }} </td>
                    <td> {{ $transaksi->alamat }} </td>
                    <td> {{ $transaksi->jumlah }} </td>
                    <td>
                        <a class="btn btn-warning" href="#"><i class="fa fa-cog"></i> Edit</a> <br>
                        <div class="mt-2"></div>
                        <form action="#" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i> Delete</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection