routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/order', function () {
    return view('pembeli.order');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// GET EACH PAGE WITH RESOURCES
Route::resource('/adminUtama', 'AdminController');
Route::resource('/kandang', 'KandangController')->middleware('peternak');
Route::resource('/pembeli', 'PembeliController')->middleware('penjual');
Route::resource('/transaksi', 'TransaksiController');
Route::get('/tableTransaksi', 'TransaksiController@tampilTransaksiTabel');

app/Kandang.php
<?php

namespace Peternakan;

use Illuminate\Database\Eloquent\Model;

class Kandang extends Model
{
    protected $fillable = ['user_id', 'suhu_1', 'kelembapan_1', 'suhu_2', 'kelembapan_2', 'suhu_3', 'kelembapan_3', 'stok', 'harga', 'gambar'];
    
    public function user()
    {
     	return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function transaksis()
    {
        return $this->hasMany('Peternakan\Transaksi', 'peternak_id', 'id');
    }

}

app/Http/Controllers/KandangController.php
<?php

namespace Peternakan\Http\Controllers;

use Peternakan\Kandang;
use Illuminate\Http\Request;
use Auth;
use Peternakan\User;
use Illuminate\Support\Facades\File;

class KandangController extends Controller
{    
    public function index()
    {
        $user = Auth::user();
        $kandangs = $user->kandang;
        // dd($kandangs);
        return view('kandang.index', compact('kandangs'));
    }


    public function create()
    {
        return view('kandang.create');
    }


    public function store(Request $request)
    {        
        $this->validate($request, [
            'suhu_1' => 'required',
            'kelembapan_1' => 'required',
            'suhu_2' => 'required',
            'kelembapan_2' => 'required',
            'suhu_3' => 'required',
            'kelembapan_3' => 'required',
            'stok' => 'required',
            'gambar' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:8192',
        ]);
            
        $kandang = new Kandang();
        $kandang->suhu_1            = $request->suhu_1;
        $kandang->kelembapan_1      = $request->kelembapan_1;
        $kandang->suhu_2            = $request->suhu_2;
        $kandang->kelembapan_2      = $request->kelembapan_2;
        $kandang->suhu_3            = $request->suhu_3;
        $kandang->kelembapan_3      = $request->kelembapan_3;
        $kandang->stok              = $request->stok;
        $kandang->gambar         = $request->gambar;
        if ($request->hasFile('gambar')) {
            $gambar = $request->file('gambar');
            $filename = 'slide' . '-' . '.' . $gambar->getClientOriginalName();
            $location = 'image/ayam/';
            $request->file('gambar')->move($location, $filename);
            $kandang->gambar = $filename;
  
        }
        $kandang->save();
        return redirect('kandang')->with('success','Berhasil menambah Kondisi Kandang');
    }


    public function show(Kandang $kandang)
    {
        $users = Auth::user();
        return view('kandang.show', compact('kandang', 'users'));
    }


    public function edit($id)
    {
        $kandang = Kandang::findOrFail($id);
        return view('kandang.edit', compact('kandang'));
    }


    public function update(Request $request, $id)
    {
        $kandang = Kandang::find($id);
        $this->validate($request, [
            'suhu_1' => 'required',
            'kelembapan_1' => 'required',
            'suhu_2' => 'required',
            'kelembapan_2' => 'required',
            'suhu_3' => 'required',
            'kelembapan_3' => 'required',
            'stok' => 'required',
            'harga' => 'required',
            'gambar' => '',
        ]);

        $kandang->suhu_1            = $request->suhu_1;
        $kandang->kelembapan_1      = $request->kelembapan_1;
        $kandang->suhu_2            = $request->suhu_2;
        $kandang->kelembapan_2      = $request->kelembapan_2;
        $kandang->suhu_3            = $request->suhu_3;
        $kandang->kelembapan_3      = $request->kelembapan_3;
        $kandang->stok              = $request->stok;
        $kandang->harga              = $request->harga;
        if ($request->hasFile('gambar')) {
            $gambar = $request->file('gambar');
            $filename = 'ayam' . '-' . $kandang->user->username . '.' . $gambar->getClientOriginalExtension();
            $location = public_path('image/ayam/');
            $request->file('gambar')->move($location, $filename);
            
            if($kandang->gambar)
            {
                $old_img = $kandang->gambar;
                $filepath = public_path().DIRECTORY_SEPARATOR.'image/ayam'.DIRECTORY_SEPARATOR.$kandang->gambar;
                try{
                    File::delete($filepath);
                }catch(FileNotFoundException $e)
                {
                    //file sudah dihapus
                }
            }
            $kandang->gambar = $filename;
        }
        $kandang->save();
        return redirect('kandang')->with('success','Berhasil mengedit Kondisi Kandang');
    }


    public function destroy(Kandang $kandang, $id)
    {
        $kandang = Kandang::findOrfail($id);

        if($kandang->gambar)
        {
            $old_img = $kandang->gambar;
            $filepath = public_path().DIRECTORY_SEPARATOR.'image/ayam'.DIRECTORY_SEPARATOR.$kandang->gambar;
            try{
                File::delete($filepath);
            }catch(FileNotFoundException $e){
                 //file sudah dihapus
            }
        }
        $kandang->delete();
    }
}

resources/views/kandang/create.blade.php
@extends('master._layout')

@section('title', 'Buat Kondisi Kandang')

@section('content')
<div class="container p-5">
    <div class="card-box">
        <h5>Buat Kondisi Kandang</h5>

        <form method="POST" action="{{ route('kandang.store') }}" enctype="multipart/form-data">
            @csrf

            <div class="form-group row">
                <label for="tanggal" class="col-md-4 col-form-label text-md-left">{{ __('Tanggal') }}</label>

                <div class="col-md-6">
                    <input id="tanggal" type="date"
                        class="form-control{{ $errors->has('tanggal') ? ' is-invalid' : '' }}" name="tanggal"
                        value="{{ old('tanggal') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="waktu" class="col-md-4 col-form-label text-md-left">{{ __('Waktu') }}</label>

                <div class="col-md-6">
                    <input id="waktu" type="time" class="form-control{{ $errors->has('waktu') ? ' is-invalid' : '' }}"
                        name="waktu" value="{{ old('waktu') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="suhu_1" class="col-md-4 col-form-label text-md-left">{{ __('Suhu 1') }}</label>

                <div class="col-md-6">
                    <input id="suhu_1" type="text" class="form-control{{ $errors->has('suhu_1') ? ' is-invalid' : '' }}"
                        name="suhu_1" value="{{ old('suhu_1') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="suhu_2" class="col-md-4 col-form-label text-md-left">{{ __('Suhu 2') }}</label>

                <div class="col-md-6">
                    <input id="suhu_2" type="text" class="form-control{{ $errors->has('suhu_2') ? ' is-invalid' : '' }}"
                        name="suhu_2" value="{{ old('suhu_2') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="suhu_3" class="col-md-4 col-form-label text-md-left">{{ __('Suhu 3') }}</label>

                <div class="col-md-6">
                    <input id="suhu_3" type="text" class="form-control{{ $errors->has('suhu_3') ? ' is-invalid' : '' }}"
                        name="suhu_3" value="{{ old('suhu_3') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="kelembapan_1" class="col-md-4 col-form-label text-md-left">{{ __('Kelembapan 1') }}</label>

                <div class="col-md-6">
                    <input id="kelembapan_1" type="text"
                        class="form-control{{ $errors->has('kelembapan_1') ? ' is-invalid' : '' }}" name="kelembapan_1"
                        value="{{ old('kelembapan_1') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="kelembapan_2" class="col-md-4 col-form-label text-md-left">{{ __('Kelembapan 1') }}</label>

                <div class="col-md-6">
                    <input id="kelembapan_2" type="text"
                        class="form-control{{ $errors->has('kelembapan_2') ? ' is-invalid' : '' }}" name="kelembapan_2"
                        value="{{ old('kelembapan_2') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="kelembapan_3" class="col-md-4 col-form-label text-md-left">{{ __('Kelembapan 1') }}</label>

                <div class="col-md-6">
                    <input id="kelembapan_3" type="text"
                        class="form-control{{ $errors->has('kelembapan_3') ? ' is-invalid' : '' }}" name="kelembapan_3"
                        value="{{ old('kelembapan_3') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="telepon" class="col-md-4 col-form-label text-md-left">{{ __('Telepon') }}</label>

                <div class="col-md-6">
                    <input id="telepon" type="text"
                        class="form-control{{ $errors->has('telepon') ? ' is-invalid' : '' }}" name="telepon"
                        value="{{ old('telepon') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="stok" class="col-md-4 col-form-label text-md-left">{{ __('Stok') }}</label>

                <div class="col-md-6">
                    <input id="stok" type="text" class="form-control{{ $errors->has('stok') ? ' is-invalid' : '' }}"
                        name="stok" value="{{ old('stok') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="harga" class="col-md-4 col-form-label text-md-left">{{ __('Harga') }}</label>

                <div class="col-md-6">
                    <input id="harga" type="text" class="form-control{{ $errors->has('harga') ? ' is-invalid' : '' }}"
                        name="harga" value="{{ old('harga') }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="gambar" class="col-md-4 col-form-label text-md-left">{{ __('Gambar') }}</label>

                <div class="col-md-6">
                    <input type="file" class="form-control-file{{ $errors->has('gambar') ? ' is-invalid' : '' }}" id="gambar"
                    name="gambar" value="{{ old('gambar') }}" required>
                </div>
            </div>

            <div class="form-group row mb-0">
                <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Register') }}
                    </button>
                </div>
            </div>

            @include('error')
        </form>
    </div>
</div>
@endsection

resources/views/kandang/edit.blade.php
@extends('master._layout') @section('title', 'Edit Kondisi Kandang') @section('content')
<div class="container p-5">
    <div class="card-box">
        <h2 class="">Edit Kondisi Kandang</h2>

        <form method="POST" action="{{ route('kandang.update', $kandang->id) }}" enctype="multipart/form-data">
            @method('PATCH') @csrf

            <div class="form-group row">
                <label for="suhu_1" class="col-md-4 col-form-label text-md-left">{{ __('Suhu 1') }}</label>

                <div class="col-md-6">
                    <input id="suhu_1" type="text" class="form-control" name="suhu_1" value="{{ old('suhu_1', $kandang->suhu_1) }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="suhu_2" class="col-md-4 col-form-label text-md-left">{{ __('Suhu 2') }}</label>

                <div class="col-md-6">
                    <input id="suhu_2" type="text" class="form-control" name="suhu_2" value="{{ old('suhu_2', $kandang->suhu_2) }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="suhu_3" class="col-md-4 col-form-label text-md-left">{{ __('Suhu 3') }}</label>

                <div class="col-md-6">
                    <input id="suhu_3" type="text" class="form-control" name="suhu_3" value="{{ old('suhu_1', $kandang->suhu_1) }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="kelembapan_1" class="col-md-4 col-form-label text-md-left">{{ __('Kelembapan 1') }}</label>

                <div class="col-md-6">
                    <input id="kelembapan_1" type="text" class="form-control" name="kelembapan_1" value="{{ old('kelembapan_1', $kandang->kelembapan_1) }}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="kelembapan_2" class="col-md-4 col-form-label text-md-left">{{ __('Kelembapan 1') }}</label>

                <div class="col-md-6">
                    <input id="kelembapan_2" type="text" class="form-control" name="kelembapan_2" value="{{old('kelembapan_2', $kandang->kelembapan_2)}}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="kelembapan_3" class="col-md-4 col-form-label text-md-left">{{ __('Kelembapan 1') }}</label>

                <div class="col-md-6">
                    <input id="kelembapan_3" type="text" class="form-control" name="kelembapan_3" value="{{old('kelembapan_3', $kandang->kelembapan_3)}}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="stok" class="col-md-4 col-form-label text-md-left">{{ __('Stok') }}</label>

                <div class="col-md-6">
                    <input id="stok" type="text" class="form-control" name="stok" value="{{old('stok', $kandang->stok)}}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="harga" class="col-md-4 col-form-label text-md-left">{{ __('Harga') }}</label>

                <div class="col-md-6">
                    <input id="harga" type="text" class="form-control" name="harga" value="{{old('harga', $kandang->harga)}}" required>
                </div>
            </div>

            <div class="form-group row">
                <label for="gambar" class="col-md-4 col-form-label text-md-left">{{ __('Gambar') }}</label>

                <div class="col-md-6">
                    <input type="file" class="form-control-file" id="gambar" name="gambar" value="{{old('gambar', $kandang->gambar)}}">
                </div>
                <div class="col-md-6"></div>
                <div class="col-md-6">
                    <img src="{{ URL::asset('image/ayam/'.$kandang->gambar)}}" alt="Ayam" style="max-width: 200px;">
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">
                        {{ __('Edit') }}
                    </button>
                </div>
            </div>

            @include('error')
        </form>
    </div>
</div>
@endsection

resources/views/kandang/index.blade.php
@extends('master._layout')

@section('title', 'Peternak')

@section('nm')
Kandang
@endsection

@section('content')

<div class="container mt-2">
    <div class="card-box">
        <ul class="ul-nav">
            <li><a href="/kandang" class="btn btn-info">Home</a></li>
            <li>
                <a class="btn btn-dark" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();"> {{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
        </ul>
    </div>
</div>

<div class="container pt-2">
    @foreach ($kandangs as $kandang)
    <div class="card-box">
        <h3>Selamat datang {{ $kandang->user->username }}</h3>
    </div>
    @endforeach
</div>

<div class="container">
    <div class="mt-3 mb-3">
    </div>
    <div class="card-box--kandang">
        @foreach ($kandangs as $kandang)
        <h5>Kondisi Kandang Anda </h5>
        <span class="card-box__tanggal">Tanggal : {{ \Carbon\Carbon::parse($kandang->tanggal)->format('d-m-Y')}}</span>
        <span class="card-box__tanggal">Waktu : {{ \Carbon\Carbon::parse($kandang->waktu)->format('H:m:i')}}</span>
        <span class="card-box__tanggal">Stok : {{ $kandang->stok }}</span>
        <div class="card-box--kandang__img">
            @if($kandang->gambar)
                <img src="{{ URL::asset('image/ayam/'.$kandang->gambar)}}" alt="Ayam" style="max-width: 200px;">
            @else
                <img src="{{ URL::asset('image/ayamku.jpg') }}" class="rounded" />
            @endif
        </div>
        <a href="/kandang/{{ $kandang->id }}" class="btn btn-success"> <i class="fa fa-eye"></i> Show Detail</a>
        @endforeach
    </div>
</div>

@endsection

resources/views/kandang/show.blade.php
@extends('master._layout')

@section('title', 'Lihat Peternak')

@section('content')

<div class="container mt-2">
    <div class="card-box">
        <ul class="ul-nav">
            <li><a href="/kandang" class="btn btn-info">Home</a></li>
            <li>
                <a class="btn btn-dark" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();"> {{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
        </ul>
    </div>
</div>

<div class="container">
    <div class="card-box">
        <div class="title-kandang">
            <h4 class="text-center">Kondisi Kandang Anda</h4>
            <a href="{{ route('kandang.edit',$kandang->id)}}" class="btn btn-secondary"><i class="fa fa-cog"> Edit
                    Kondisi Kandang</i></a>
        </div>
        <div class="row d-flex align-items-lg-center">
            <div class="col-md-12">
                <div class="card-box--kandang__img text-center mb-2">
                    @if($kandang->gambar)
                    <img src="{{ URL::asset('image/ayam/'.$kandang->gambar)}}" alt="Ayam" style="max-width: 200px;">
                    @else
                    <img src="{{ URL::asset('image/ayamku.jpg') }}" class="rounded" />
                    @endif
                </div>
            </div>
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card text-center">
                            <div class="card-header">
                                Suhu 1
                            </div>
                            <div class="card-body">
                                <h3 class="card-title"> <i class="fas fa-thermometer-half"></i>
                                    {{ $kandang->suhu_1}}&deg; </h3>
                                <p class="card-text">Suhu kandang anda {{ $kandang->suhu_1}}&deg; </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card text-center">
                            <div class="card-header">
                                Kelembapan 1
                            </div>
                            <div class="card-body">
                                <h3 class="card-title"> <i class="fas fa-tint"></i> {{ $kandang->kelembapan_1}}% </h3>
                                <p class="card-text">Kelembapan kandang anda {{ $kandang->kelembapan_1}}% </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card text-center">
                            <div class="card-header">
                                Suhu 2
                            </div>
                            <div class="card-body">
                                <h3 class="card-title"> <i class="fas fa-thermometer-half"></i>
                                    {{ $kandang->suhu_2}}&deg; </h3>
                                <p class="card-text">Suhu kandang anda {{ $kandang->suhu_2}}&deg; </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card text-center">
                            <div class="card-header">
                                Kelembapan 2
                            </div>
                            <div class="card-body">
                                <h3 class="card-title"> <i class="fas fa-tint"></i> {{ $kandang->kelembapan_2}}% </h3>
                                <p class="card-text">Kelembapan kandang anda {{ $kandang->kelembapan_2}}% </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card text-center">
                            <div class="card-header">
                                Suhu 3
                            </div>
                            <div class="card-body">
                                <h3 class="card-title"> <i class="fas fa-thermometer-half"></i>
                                    {{ $kandang->suhu_3}}&deg; </h3>
                                <p class="card-text">Suhu kandang anda {{ $kandang->suhu_3}}&deg; </p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card text-center">
                            <div class="card-header">
                                Kelembapan 3
                            </div>
                            <div class="card-body">
                                <h3 class="card-title"> <i class="fas fa-tint"></i> {{ $kandang->kelembapan_3}}% </h3>
                                <p class="card-text">Kelembapan kandang anda {{ $kandang->kelembapan_3}}% </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card text-center">
                    <div class="card-header">
                        Stok Anda
                    </div>
                    <div class="card-body">
                        <h3 class="card-title"> <i class="fas fa-boxes"></i> {{ $kandang->stok}} item</h3>
                        <p class="card-text">Stok anda {{ $kandang->stok}} item</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card text-center">
                    <div class="card-header">
                        Harga
                    </div>
                    <div class="card-body">
                        <h3 class="card-title"> <i class="fas fa-money-bill-wave"></i>
                            {{ number_format($kandang->harga, 2, ',', '.') }} Rupiah</h3>
                        <p class="card-text">Harga {{ number_format($kandang->harga, 2, ',', '.') }} Rupiah</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection